### PR TITLE
fix(popup-global / sidenav): disabled scroll when popup open, fixed n…

### LINKED ISSUE #33: SideMenu not working properly with Hal Side menu due to scroll block
Try scrolling a bit down and opening amat dialog. The sidenav will then become broken due to its display property

### PR DESCRIPTION
**Pull request by frideska**
Disable scroll + Navbar bug (resolve #33)

### CODE REVIEW

File: src/app/docs-pages/popup-global-doc/popup-global-doc.component.ts [hunk 1]
```diff
@@ -70,15 +70,31 @@ onClose() {
...
+  // Disable scroll on background
+  disableScroll(scrollTop: number) {
+    document.body.style.position = 'fixed';
+    document.body.style.top = `-${scrollTop}px`;
+  }
+
+  resetScroll(scrollTop: number) {
+    document.body.style.position = '';
+    document.body.style.top = `-${scrollTop}px`;
+    window.scrollTo(0, scrollTop);
```
Comment (JGH153) [inline src/app/docs-pages/popup-global-doc/popup-global-doc.component.ts]: Kan dette løses med overlay.scrollStrategies.block();?

**Review by JGH153 — APPROVED** [review]
